protected/models/Publishers.php
<?php

/**
 * This is the model class for table "tm_publisher".
 *
 * The followings are the available columns in table 'tm_publisher':
 * @property integer $TM_PR_Id
 * @property string $TM_PR_Name
 * @property string $TM_PR_CreatedOn
 * @property integer $TM_PR_CreatedBy
 * @property integer $TM_PR_Status
 */
class Publishers extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'tm_publisher';
	}

    public function behaviors() {
        return array(
            'ERememberFiltersBehavior' => array(
                'class' => 'application.components.ERememberFiltersBehavior',
                'defaults'=>array(),           /* optional line */
                'defaultStickOnClear'=>false   /* optional line */
            ),
        );
    }
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('TM_PR_Name', 'required'),
			array('TM_PR_CreatedBy, TM_PR_Status', 'numerical', 'integerOnly'=>true),
			array('TM_PR_Name', 'length', 'max'=>250),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('TM_PR_Id, TM_PR_Name, TM_PR_CreatedOn, TM_PR_CreatedBy, TM_PR_Status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'question'=>array(self::HAS_MANY, 'Questions', 'TM_QN_Publisher_Id'),
            'studenttest'=>array(self::HAS_MANY, 'StudentTest', 'TM_STU_TT_Publisher_Id'),
            'mock'=>array(self::HAS_MANY, 'Mock', 'TM_MK_Publisher_Id'),
			'plan'=>array(self::HAS_MANY, 'Plan', 'TM_PN_Publisher_Id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'TM_PR_Id' => 'ID',
			'TM_PR_Name' => 'Publisher Name',
			'TM_PR_CreatedOn' => 'Created On',
			'TM_PR_CreatedBy' => 'Created By',
			'TM_PR_Status' => 'Status',
		);
	}
    /*public function scopes()
    {
        return array(
            'active' => array(
                'condition' => 'status=0',
            ),
            'disabled' => array(
                'condition' => 'status=1',
            ),
        );
    }*/
    public static function itemAlias($type,$code=NULL) {
        $_items = array(

            'PublisherStatus' => array(
                '0' => ('Active'),
                '1' => ('Inactive'),
            ),
        );
        if (isset($code))
            return isset($_items[$type][$code]) ? $_items[$type][$code] : false;
        else
            return isset($_items[$type]) ? $_items[$type] : false;
    }
	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('TM_PR_Id',$this->TM_PR_Id);
		$criteria->compare('TM_PR_Name',$this->TM_PR_Name,true);
		$criteria->compare('TM_PR_CreatedOn',$this->TM_PR_CreatedOn,true);
		$criteria->compare('TM_PR_CreatedBy',$this->TM_PR_CreatedBy);
		$criteria->compare('TM_PR_Status',$this->TM_PR_Status);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria, 'pagination'=>array(
                'pageSize'=>30,
            ),
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Publishers the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/PublishersController.php
<?php

class PublishersController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/admincolumn2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			/*array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array(),
				'users'=>array('@'),
			),*/
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','index','view','create','update'),
                'users'=>UserModule::getSuperAdmins(),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Publishers;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Publishers']))
		{
			$model->attributes=$_POST['Publishers'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->TM_PR_Id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Publishers']))
		{
			$model->attributes=$_POST['Publishers'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->TM_PR_Id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Publishers');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Publishers('search');
/*		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Publishers']))
			$model->attributes=$_GET['Publishers'];*/

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Publishers the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Publishers::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Publishers $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='publishers-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/publishers/_form.php
<?php
/* @var $this PublishersController */
/* @var $model Publishers */
/* @var $form CActiveForm */
Yii::app()->clientScript->registerScript('cancel', "
    $('.cancelbtn').click(function(){
        window.location = '".Yii::app()->createUrl('publishers/admin')."';
    });
");
?>

<div class="row brd1">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'publishers-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>
<div class="panel-body form-horizontal payment-form">
    <div class="well well-sm"><strong>Fields with <span class="required">*</span> are required.</strong></div>
	<?php /*echo $form->errorSummary($model); */?>
    <div class="form-group">
		<?php echo $form->labelEx($model,'TM_PR_Name',array('class'=>'col-sm-3 control-label')); ?>
        <div class="col-sm-9">
            <?php echo $form->textField($model,'TM_PR_Name',array('size'=>60,'maxlength'=>250,'class'=>'form-control')); ?>
            <?php echo $form->error($model,'TM_PR_Name'); ?>
        </div>
	</div>
    <div class="form-group">
        <?php echo $form->labelEx($model,'TM_PR_Status',array('class'=>'col-sm-3 control-label')); ?>
        <div class="col-sm-9">
            <?php echo $form->hiddenField($model,'TM_PR_CreatedBy',array('value'=>Yii::app()->user->id)); ?>
            <?php echo $form->dropDownList($model,'TM_PR_Status',Publishers::itemAlias('PublisherStatus'),array('class'=>'form-control')); ?>
            <?php echo $form->error($model,'TM_PR_Status'); ?>
        </div>
	</div>

    <div class="form-group">
        <div class="row">
        <div class="col-sm-3 pull-right">
		    <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save',array('class'=>'btn btn-warning btn-lg btn-block')); ?>
        </div>
            <div class="col-lg-3 pull-right">
                <button class="btn btn-warning btn-lg btn-block cancelbtn" type="reset" value="Reset">Cancel</button>
            </div>
            </div>
	</div>
</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/publishers/_search.php
<?php
/* @var $this PublishersController */
/* @var $model Publishers */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'TM_PR_Id'); ?>
		<?php echo $form->textField($model,'TM_PR_Id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'TM_PR_Name'); ?>
		<?php echo $form->textField($model,'TM_PR_Name',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'TM_PR_CreatedOn'); ?>
		<?php echo $form->textField($model,'TM_PR_CreatedOn'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'TM_PR_CreatedBy'); ?>
		<?php echo $form->textField($model,'TM_PR_CreatedBy'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'TM_PR_Status'); ?>
		<?php echo $form->textField($model,'TM_PR_Status'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/publishers/_view.php
<?php
/* @var $this PublishersController */
/* @var $data Publishers */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_PR_Id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->TM_PR_Id), array('view', 'id'=>$data->TM_PR_Id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_PR_Name')); ?>:</b>
	<?php echo CHtml::encode($data->TM_PR_Name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_PR_CreatedOn')); ?>:</b>
	<?php echo CHtml::encode($data->TM_PR_CreatedOn); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_PR_CreatedBy')); ?>:</b>
	<?php echo CHtml::encode($data->TM_PR_CreatedBy); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_PR_Status')); ?>:</b>
	<?php echo CHtml::encode($data->TM_PR_Status); ?>
	<br />


</div>

protected/views/publishers/admin.php
<?php
/* @var $this PublishersController */
/* @var $model Publishers */


$this->breadcrumbs=array(
	'Publishers'=>array('admin'),
);

$this->menu=array(
	array('label'=>'Manage Publishers', 'class'=>'nav-header'),
	array('label'=>'List Publishers', 'url'=>array('admin')),
	array('label'=>'Create Publishers', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#publishers-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<h3>Manage Publishers</h3>
<div class="row brd1">
    <div class="col-lg-12">
        <?php $this->widget('zii.widgets.grid.CGridView', array(
        'id'=>'publishers-grid',
        'dataProvider'=>$model->search(),
        'filter'=>$model,
        'columns'=>array(
            'TM_PR_Name',
            array(
                'name'=>'TM_PR_Status',
                'value'=>'Publishers::itemAlias("PublisherStatus",$data->TM_PR_Status)',
                'filter'=>Publishers::itemAlias('PublisherStatus'),
            ),
            array(
                'class'=>'CButtonColumn',
                'template'=>'{view}{update}{delete}',
                'deleteButtonImageUrl'=>false,
                'updateButtonImageUrl'=>false,
                'viewButtonImageUrl'=>false,
                'buttons'=>array
                (
                    'view'=>array(
                        'label'=>'<span class="glyphicon glyphicon-eye-open"></span>',
                        'options'=>array(
                            'title'=>'View'
                        )),
                    'update'=>array(
                        'label'=>'<span class="glyphicon glyphicon-pencil"></span>',
                        'options'=>array(
                            'title'=>'Update'
                        )),
                    'delete'=>array(
                        'label'=>'<span class="glyphicon glyphicon-trash"></span>',
                        'options'=>array(

                            'title'=>'Delete',
                        ),
                    )
                ),
            ),
        ),'itemsCssClass'=>"table table-bordered table-hover table-striped"
    )); ?>
    </div><!--/span-->

</div><!--/row-->

protected/views/publishers/create.php
<?php
/* @var $this PublishersController */
/* @var $model Publishers */

$this->breadcrumbs=array(
	'Publishers'=>array('admin'),
	'Create',
);
$this->menu=array(
    array('label'=>'Manage Publishers', 'class'=>'nav-header'),
    array('label'=>'List Publishers', 'url'=>array('admin')),
);
?>

<h3>Create Publishers</h3>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/publishers/index.php
<?php
/* @var $this PublishersController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Publishers',
);

$this->menu=array(
	array('label'=>'Create Publishers', 'url'=>array('create')),
	array('label'=>'Manage Publishers', 'url'=>array('admin')),
);
?>

<h1>Publishers</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/publishers/update.php
<?php
/* @var $this PublishersController */
/* @var $model Publishers */

$this->breadcrumbs=array(
	'Publishers'=>array('admin'),
	$model->TM_PR_Id=>array('view','id'=>$model->TM_PR_Id),
	'Update',
);

$this->menu=array(
    array('label'=>'Manage Publishers', 'class'=>'nav-header'),
	array('label'=>'List Publishers', 'url'=>array('admin')),
	array('label'=>'Create Publishers', 'url'=>array('create')),
	array('label'=>'View Publishers', 'url'=>array('view', 'id'=>$model->TM_PR_Id)),

);
?>

<h3>Update <?php echo $model->TM_PR_Name; ?></h3>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/publishers/view.php
<?php
/* @var $this PublishersController */
/* @var $model Publishers */

$this->breadcrumbs=array(
	'Publishers'=>array('admin'),
	$model->TM_PR_Id,
);

$this->menu=array(
    array('label'=>'Manage Publishers', 'class'=>'nav-header'),
	array('label'=>'List Publishers', 'url'=>array('admin')),
	array('label'=>'Create Publishers', 'url'=>array('create')),
	array('label'=>'Update Publishers', 'url'=>array('update', 'id'=>$model->TM_PR_Id)),
	array('label'=>'Delete Publishers', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->TM_PR_Id),'confirm'=>'Are you sure you want to delete this item?')),

);
?>

<h3>View <?php echo $model->TM_PR_Name; ?></h3>
<div class="row brd1">
    <div class="col-lg-12">
        <?php
        $id=$model->TM_PR_Status;
        $userid=$model->TM_PR_CreatedBy;
        $this->widget('zii.widgets.CDetailView', array(
            'data'=>$model,
            'attributes'=>array(
                'TM_PR_Id',
                'TM_PR_Name',
                'TM_PR_CreatedOn',
                array(
                    'label'=>'Created By',
                    'type'=>'raw',
                    'value'=>User::model()->GetUser($userid),
                ),
                array(
                    'label'=>'Status',
                    'type'=>'raw',
                    'value'=>Publishers::itemAlias("PublisherStatus",$id),
                ),
            ),
            'htmlOptions' => array('class' => 'table table-bordered table-hover')
        )); ?>
    </div>
</div>