protected/models/Standard.php
<?php

/**
 * This is the model class for table "{{standard}}".
 *
 * The followings are the available columns in table '{{standard}}':
 * @property integer $TM_SD_Id
 * @property integer $TM_SD_Syllabus_Id
 * @property string $TM_SD_Name
 * @property string $TM_SD_CreatedOn
 * @property integer $TM_SD_CreatedBy
 * @property integer $TM_SD_Status
 */
class Standard extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{standard}}';
	}

    public function behaviors() {
        return array(
            'ERememberFiltersBehavior' => array(
                'class' => 'application.components.ERememberFiltersBehavior',
                'defaults'=>array(),           /* optional line */
                'defaultStickOnClear'=>false   /* optional line */
            ),
        );
    }
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('TM_SD_Syllabus_Id,TM_SD_Name', 'required'),
			array('TM_SD_CreatedBy, TM_SD_Status', 'numerical', 'integerOnly'=>true),
			array('TM_SD_Name', 'length', 'max'=>250),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('TM_SD_Id, TM_SD_Syllabus_Id,TM_SD_Name, TM_SD_CreatedOn, TM_SD_CreatedBy, TM_SD_Status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
            'question'=>array(self::HAS_MANY, 'Questions', 'TM_QN_Standard_Id'),
            'chapter'=>array(self::HAS_MANY, 'Chapter', 'TM_TP_Standard_Id'),
            'mock'=>array(self::HAS_MANY, 'Mock', 'TM_MK_Standard_Id'),
            'admins'=>array(self::HAS_MANY, 'Adminstandards', 'TM_SA_Standard_Id'),
            'plan'=>array(self::HAS_MANY, 'Plan', 'TM_PN_Standard_Id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'TM_SD_Id' => 'ID',
			'TM_SD_Syllabus_Id' => 'Syllabus',
			'TM_SD_Name' => 'Standard',
			'TM_SD_CreatedOn' => 'Created On',
			'TM_SD_CreatedBy' => 'Created By',
			'TM_SD_Status' => 'Status',
		);
	}

    public static function itemAlias($type,$code=NULL) {
        $_items = array(

            'StandardStatus' => array(
                '0' => ('Active'),
                '1' => ('Inactive'),
            ),
        );
        if (isset($code))
            return isset($_items[$type][$code]) ? $_items[$type][$code] : false;
        else
            return isset($_items[$type]) ? $_items[$type] : false;
    }
	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('TM_SD_Id',$this->TM_SD_Id);
		$criteria->compare('TM_SD_Syllabus_Id',$this->TM_SD_Syllabus_Id);
		$criteria->compare('TM_SD_Name',$this->TM_SD_Name,true);
		$criteria->compare('TM_SD_CreatedOn',$this->TM_SD_CreatedOn,true);
		$criteria->compare('TM_SD_CreatedBy',$this->TM_SD_CreatedBy);
		$criteria->compare('TM_SD_Status',$this->TM_SD_Status);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria, 'pagination'=>array(
                'pageSize'=>30,
            ),
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Standard the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/StandardController.php
<?php

class StandardController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
    public $layout='//layouts/admincolumn2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
/*			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array(),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array(),
				'users'=>array('@'),
			),*/
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','create','update','index','view'),
                'users'=>UserModule::getSuperAdmins(),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Standard;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Standard']))
		{
			$model->attributes=$_POST['Standard'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->TM_SD_Id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Standard']))
		{
			$model->attributes=$_POST['Standard'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->TM_SD_Id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Standard');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Standard('search');
/*		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Standard']))
			$model->attributes=$_GET['Standard'];*/

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Standard the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Standard::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Standard $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='standard-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/standard/_form.php
<?php
/* @var $this StandardController */
/* @var $model Standard */
/* @var $form CActiveForm */
Yii::app()->clientScript->registerScript('cancel', "
    $('.cancelbtn').click(function(){
        window.location = '".Yii::app()->createUrl('standard/admin')."';
    });
");
?>

<div class="row brd1">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'standard-form',
	// Please note: When you enable ajax validation, make sure the corresponding
	// controller action is handling ajax validation correctly.
	// There is a call to performAjaxValidation() commented in generated controller code.
	// See class documentation of CActiveForm for details on this.
	'enableAjaxValidation'=>false,
)); ?>
    <div class="panel-body form-horizontal payment-form">
        <div class="well well-sm"><strong>Fields with <span class="required">*</span> are required</strong></div>
        <div class="form-group">
            <?php echo $form->labelEx($model,'TM_SD_Syllabus_Id',array('class'=>'col-sm-3 control-label'));?>
            <div class="col-sm-9">
                <?php echo $form->dropDownList($model,'TM_SD_Syllabus_Id',CHtml::listData(Syllabus::model()->findAll(array('order' => 'TM_SB_Name')),'TM_SB_Id','TM_SB_Name'),array('empty'=>'Select','class'=>'form-control')); ?>
                <?php echo $form->error($model,'TM_SD_Syllabus_Id'); ?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->labelEx($model,'TM_SD_Name',array('class'=>'col-sm-3 control-label'));?>
            <div class="col-sm-9">
                <?php echo $form->textField($model,'TM_SD_Name',array('size'=>60,'maxlength'=>250,'class'=>'form-control')); ?>
                <?php echo $form->error($model,'TM_SD_Name'); ?>
            </div>
        </div>

        <!--<div class="row">
            <?php /*echo $form->labelEx($model,'TM_SD_CreatedOn'); */?>
            <?php /*echo $form->textField($model,'TM_SD_CreatedOn'); */?>
            <?php /*echo $form->error($model,'TM_SD_CreatedOn'); */?>
        </div>

        <div class="row">
            <?php /*echo $form->labelEx($model,'TM_SD_CreatedBy'); */?>
            <?php /*echo $form->textField($model,'TM_SD_CreatedBy'); */?>
            <?php /*echo $form->error($model,'TM_SD_CreatedBy'); */?>
        </div>-->

        <div class="form-group">
            <?php echo $form->labelEx($model,'TM_SD_Status',array('class'=>'col-sm-3 control-label')); ?>
            <div class="col-sm-9">
                <?php echo $form->hiddenField($model,'TM_SD_CreatedBy',array('value'=>Yii::app()->user->id)); ?>
                <?php echo $form->dropDownList($model,'TM_SD_Status',Standard::itemAlias('StandardStatus'),array('class'=>'form-control')); ?>
                <?php echo $form->error($model,'TM_SD_Status'); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="raw">


            <div class="col-sm-3 pull-right">
                <?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save',array('class'=>'btn btn-warning btn-lg btn-block')); ?>
            </div>
                <div class="col-lg-3 pull-right">
                    <button class="btn btn-warning btn-lg btn-block cancelbtn" type="button" value="Reset">Cancel</button>
                </div>
            </div>
        </div>

        <?php $this->endWidget(); ?>
    </div>
</div><!-- form -->

protected/views/standard/_search.php
<?php
/* @var $this StandardController */
/* @var $model Standard */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'TM_SD_Id'); ?>
		<?php echo $form->textField($model,'TM_SD_Id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'TM_SD_Name'); ?>
		<?php echo $form->textField($model,'TM_SD_Name',array('size'=>60,'maxlength'=>250)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'TM_SD_CreatedOn'); ?>
		<?php echo $form->textField($model,'TM_SD_CreatedOn'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'TM_SD_CreatedBy'); ?>
		<?php echo $form->textField($model,'TM_SD_CreatedBy'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'TM_SD_Status'); ?>
		<?php echo $form->textField($model,'TM_SD_Status'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/views/standard/_view.php
<?php
/* @var $this StandardController */
/* @var $data Standard */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_SD_Id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->TM_SD_Id), array('view', 'id'=>$data->TM_SD_Id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_SD_Name')); ?>:</b>
	<?php echo CHtml::encode($data->TM_SD_Name); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_SD_CreatedOn')); ?>:</b>
	<?php echo CHtml::encode($data->TM_SD_CreatedOn); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_SD_CreatedBy')); ?>:</b>
	<?php echo CHtml::encode($data->TM_SD_CreatedBy); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('TM_SD_Status')); ?>:</b>
	<?php echo CHtml::encode($data->TM_SD_Status); ?>
	<br />


</div>

protected/views/standard/admin.php
<?php
/* @var $this StandardController */
/* @var $model Standard */

$this->breadcrumbs=array(
	'Standards'=>array('admin'),
	'Manage',
);

$this->menu=array(
    array('label'=>'Manage Standard', 'class'=>'nav-header'),
	array('label'=>'List Standard', 'url'=>array('admin')),
	array('label'=>'Create Standard', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#standard-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>
<h3>Manage Standards</h3>
<div class="row brd1">
    <div class="col-lg-12">
        <?php $this->widget('zii.widgets.grid.CGridView', array(
            'id'=>'standard-grid',
            'dataProvider'=>$model->search(),
            'filter'=>$model,
            'columns'=>array(
                'TM_SD_Name',
                array(
                    'name'=>'TM_SD_Syllabus_Id',
                    'value'=>'Syllabus::model()->findByPk($data->TM_SD_Syllabus_Id)->TM_SB_Name',
                    'filter'=>CHtml::listData(Syllabus::model()->findAll(array('order' => 'TM_SB_Name')),'TM_SB_Id','TM_SB_Name'),
                ),
                array(
                    'name'=>'TM_SD_Status',
                    'value'=>'Standard::itemAlias("StandardStatus",$data->TM_SD_Status)',
                    'filter'=>Standard::itemAlias("StandardStatus"),
                ),
                array(
                    'class'=>'CButtonColumn',
                    'template'=>'{view}{update}{delete}',
                    'deleteButtonImageUrl'=>false,
                    'updateButtonImageUrl'=>false,
                    'viewButtonImageUrl'=>false,
                    'buttons'=>array
                    (
                        'view'=>array(
                            'label'=>'<span class="glyphicon glyphicon-eye-open"></span>',
                            'options'=>array(
                                'title'=>'View'
                            )),
                        'update'=>array(
                            'label'=>'<span class="glyphicon glyphicon-pencil"></span>',
                            'options'=>array(
                                'title'=>'Update'
                            )),
                        'delete'=>array(
                            'label'=>'<span class="glyphicon glyphicon-trash"></span>',
                            'options'=>array(

                                'title'=>'Delete',
                            ),
                        )
                    ),
                ),
            ),'itemsCssClass'=>"table table-bordered table-hover table-striped"
        )); ?>
    </div>
</div>

protected/views/standard/create.php
<?php
/* @var $this StandardController */
/* @var $model Standard */

$this->breadcrumbs=array(
	'Standards'=>array('admin'),
	'Create',
);

$this->menu=array(
    array('label'=>'Manage Standard', 'class'=>'nav-header'),
	array('label'=>'List Standard', 'url'=>array('admin')),

);
?>

<h3>Create Standard</h3>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/standard/index.php
<?php
/* @var $this StandardController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Standards',
);

$this->menu=array(
	array('label'=>'Create Standard', 'url'=>array('create')),
	array('label'=>'Manage Standard', 'url'=>array('admin')),
);
?>

<h1>Standards</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/standard/update.php
<?php
/* @var $this StandardController */
/* @var $model Standard */

$this->breadcrumbs=array(
	'Standards'=>array('admin'),
	$model->TM_SD_Id=>array('view','id'=>$model->TM_SD_Id),
	'Update',
);

$this->menu=array(
    array('label'=>'Manage Standard', 'class'=>'nav-header'),
	array('label'=>'List Standard', 'url'=>array('admin')),
	array('label'=>'Create Standard', 'url'=>array('create')),
	array('label'=>'View Standard', 'url'=>array('view', 'id'=>$model->TM_SD_Id)),

);
?>

<h3>Update <?php echo $model->TM_SD_Name; ?></h3>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/standard/view.php
<?php
/* @var $this StandardController */
/* @var $model Standard */

$this->breadcrumbs=array(
	'Standards'=>array('admin'),
	$model->TM_SD_Id,
);

$this->menu=array(
    array('label'=>'Manage Standard', 'class'=>'nav-header'),
	array('label'=>'List Standard', 'url'=>array('admin')),
	array('label'=>'Create Standard', 'url'=>array('create')),
	array('label'=>'Update Standard', 'url'=>array('update', 'id'=>$model->TM_SD_Id)),
	array('label'=>'Delete Standard', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->TM_SD_Id),'confirm'=>'Are you sure you want to delete this item?')),

);
?>

<h3>View <?php echo $model->TM_SD_Name; ?></h3>
<div class="row brd1">
    <div class="col-lg-12">
        <?php
        $id=$model->TM_SD_Status;
        $userid=$model->TM_SD_CreatedBy;
        $this->widget('zii.widgets.CDetailView', array(
            'data'=>$model,
            'attributes'=>array(
                'TM_SD_Id',
                array(
                    'name'=>'TM_SD_Syllabus_Id',
                    'type'=>'raw',
                    'value'=>Syllabus::model()->findByPk($model->TM_SD_Syllabus_Id)->TM_SB_Name,
                ),
                'TM_SD_Name',
                'TM_SD_CreatedOn',
                array(
                    'label'=>'Created By',
                    'type'=>'raw',
                    'value'=>User::model()->GetUser($userid),
                ),
                array(
                    'label'=>'Status',
                    'type'=>'raw',
                    'value'=>Standard::itemAlias("StandardStatus",$id),
                ),
            ),
            'htmlOptions' => array('class' => 'table table-bordered table-hover')
        )); ?>
    </div>
</div>